import Foundation
import PackagePlugin

@main
struct VersionGeneratorPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let outputDir = context.pluginWorkDirectoryURL
        let outputFile = outputDir.appending(path: "GeneratedBuildInfo.swift")

        let script = """
            #!/bin/sh
            set -e

            OUTPUT_FILE="$1"

            # Version: env var first, then git describe, fallback to empty string
            VERSION="${AP_RELAY_VERSION:-}"
            if [ -z "$VERSION" ] && command -v git >/dev/null 2>&1; then
                VERSION=$(git describe --tags --always 2>/dev/null || echo "")
            fi

            # Commit: env var first, then git rev-parse, fallback to empty string
            COMMIT="${SOURCE_COMMIT:-}"
            if [ -z "$COMMIT" ] && command -v git >/dev/null 2>&1; then
                COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "")
            fi

            cat > "$OUTPUT_FILE" << SWIFT
            // Auto-generated by VersionGeneratorPlugin — do not edit
            enum GeneratedBuildInfo {
                static let version = "$VERSION"
                static let commit = "$COMMIT"
            }
            SWIFT
            """

        let scriptFile = outputDir.appending(path: "generate-version.sh")
        try script.write(to: scriptFile, atomically: true, encoding: .utf8)

        return [
            .prebuildCommand(
                displayName: "Generate build version info",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: [scriptFile.path(percentEncoded: false), outputFile.path(percentEncoded: false)],
                outputFilesDirectory: outputDir
            ),
        ]
    }
}
